export const answers = [
    { color: 'blue', answer: 'Бесспорно' },
    { color: 'blue', answer: 'Предрешено' },
    { color: 'blue', answer: 'Никаких сомнений' },
    { color: 'blue', answer: 'Определённо да' },
    { color: 'blue', answer: 'Можешь быть уверен в этом' },
    { color: 'green', answer: 'Мне кажется - "да"' },
    { color: 'green', answer: 'Вероятнее всего' },
    { color: 'green', answer: 'Хорошие перспективы' },
    { color: 'green', answer: 'Знаки говорят  - "да"' },
    { color: 'green', answer: 'Да' },
    { color: 'yellow', answer: 'Пока не ясно, попробуй ещё' },
    { color: 'yellow', answer: 'Спроси позже' },
    { color: 'yellow', answer: 'Лучше не рассказывать' },
    { color: 'yellow', answer: 'Сейчас нельзя предсказать' },
    { color: 'yellow', answer: 'Сконцентрируйся и спроси опять' },
    { color: 'red', answer: 'Даже не думай' },
    { color: 'red', answer: 'Мой ответ - "нет"' },
    { color: 'red', answer: 'По моим данным - "нет"' },
    { color: 'red', answer: 'Перспективы не очень хорошие' },
    { color: 'red', answer: 'Весьма сомнительно' },
]
